export { default as Home } from './Home/Home'
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword'
export { default as Login } from './Login/Login'
export { default as Page404 } from './Page404/Page404'
export { default as Profile } from './Profile/Profile'
export { default as Register } from './Register/Register'
export { default as ResetPassword } from './ResetPassword/ResetPassword'
